package com.github.manolo8.darkbot.core.api;

public enum Capability {
    LOGIN,
    ATTACH,
    INITIALLY_SHOWN,
    CREATE_WINDOW_THREAD,
    BACKGROUND_ONLY,

    ALL_KEYBINDS_SUPPORT, // Support for key clicks like "ctrl"

    PROXY,
    WINDOW_POSITION,

    HANDLER_CLEAR_CACHE,
    HANDLER_CLEAR_RAM,
    HANDLER_GAME_QUALITY,
    HANDLER_VOLUME,
    HANDLER_TRANSPARENCY,
    HANDLER_CLIENT_SIZE,
    HANDLER_MIN_CLIENT_SIZE,
    HANDLER_FLASH_PATH,
    HANDLER_INTERNET_READ_TIME,
    HANDLER_CPU_USAGE,
    HANDLER_RAM_USAGE,

    DIRECT_USE_ITEM,
    DIRECT_LIMIT_FPS,
    DIRECT_ENTITY_LOCK,
    DIRECT_ENTITY_SELECT,
    DIRECT_MOVE_SHIP,
    DIRECT_COLLECT_BOX,
    DIRECT_REFINE,
    DIRECT_CALL_METHOD,
    DIRECT_POST_ACTIONS
}
